server.port=8208
spring.application.name=service-task
spring.profiles.active=dev

spring.cloud.nacos.discovery.server-addr=192.168.88.134:8848

spring.rabbitmq.host=192.168.88.134
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
