server.port=8205
spring.application.name=service-oss
spring.profiles.active=dev


spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB


aliyun.oss.file.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.oss.file.keyid=YOUR_ALIYUN_ACCESS_KEY_ID
aliyun.oss.file.keysecret=YOUR_ALIUN_ACCESS_KEY_SECRET

aliyun.oss.file.bucketname=yyhgtest-0620

spring.cloud.nacos.discovery.server-addr=192.168.88.134:8848
